---
- name: Set variables
  set_fact:
    _gpdb_config: "{{ gpdb_default_config | combine(gpdb_config, recursive=True) }}"
    _tpcds_config: "{{ tpcds_default_config | combine(tpcds_config, recursive=True) }}"
- set_fact:
    _datagen_path: "{{ _tpcds_config.datagen_path_prefix }}_s{{ _tpcds_config.datagen_scale }}"
    _tpcds_parallelism: "{{ ansible_facts['processor_vcpus'] }}"

- include: gpdb_tpcds.yaml
  environment: "{{ _gpdb_config.gpdb_env }}"
