---
- name: Set variables
  set_fact:
    _gpdb_tpcds_config: "{{ gpdb_tpcds_default_config | combine(gpdb_tpcds_config | default({}), recursive=True) }}"
- set_fact:
    _datagen_path: "{{ _gpdb_tpcds_config.datagen_path_prefix }}_s{{ _gpdb_tpcds_config.datagen_scale }}"
    _tpcds_parallelism: "{{ ansible_facts['processor_vcpus'] }}"

- include: gpdb_tpcds.yaml
  environment: "{{ _gpdb_tpcds_config.gpdb_env }}"
