---
- name: Find DDL files
  find:
    path: "{{  _tpcds_config.tpcds_path }}/03_ddl/"
    patterns: "*.postgresql.*.sql"
  register: ddl_sql

- name: Execute DDLs for database {{ database }}
  command :  "psql -v ON_ERROR_STOP=1 -f {{ psql_file.path }}"
  environment:
    PGDATABASE: "{{ database }}"
  with_items: "{{ ddl_sql.files | sort(attribute='path') }}"
  loop_control:
    loop_var: psql_file
