---
- name: remove flag file
  file:
    path: "{{tpcds_path}}/log/end_ddl.log"
    state: absent

- name: Run DDL script
  command :  "{{postgres_install_path}}/psql -v ON_ERROR_STOP=1 -f {{psql_file}}"
  environment:
    PGDATABASE: "{{database.database}}"
    PGOPTIONS: '-c default_table_access_method={{database.default_am}}'
  with_items: "{{ lookup('fileglob', tpcds_path + '/03_ddl/*.postgresql.*.sql', wantlist=True) | sort }}"
  loop_control:
    loop_var: psql_file
