---
- name: Set variables
  set_fact:
    _postgres_config: "{{ postgres_default_config | combine(postgres_config, recursive=True) }}"
    _tpcds_config: "{{ tpcds_default_config | combine(tpcds_config, recursive=True) }}"
- set_fact:
    _datagen_path: "{{ _tpcds_config.datagen_path_prefix }}_s{{ _tpcds_config.datagen_scale }}"

- include: tpcds.yaml
  environment: "{{ _postgres_config.postgres_env }}"
