---
gpdb_tpcds_default_config:
    tpcds_repo: https://github.com/tvesely/TPC-DS
    tpcds_version: master
    tpcds_path: "{{ ansible_env.HOME }}/workspace/TPC-DS"

    datagen_path_prefix: /tmp/tpcds_datagen
    datagen_scale: 1
    gpfdist_start_port: 2300
    databases: []
    random_distribution: no
    tpcds_tables:
      - "call_center"
      - "catalog_page"
      - "catalog_returns"
      - "catalog_sales"
      - "customer"
      - "customer_address"
      - "customer_demographics"
      - "date_dim"
      - "household_demographics"
      - "income_band"
      - "inventory"
      - "item"
      - "promotion"
      - "reason"
      - "ship_mode"
      - "store"
      - "store_returns"
      - "store_sales"
      - "time_dim"
      - "warehouse"
      - "web_page"
      - "web_returns"
      - "web_sales"
      - "web_site"
    table_distribution:
        call_center: cc_call_center_sk
        catalog_page: cp_catalog_page_sk
        catalog_returns: cr_item_sk,cr_order_number
        catalog_sales: cs_item_sk,cs_order_number
        customer: c_customer_sk
        customer_address: ca_address_sk
        customer_demographics: cd_demo_sk
        date_dim: d_date_sk
        household_demographics: hd_demo_sk
        income_band: ib_income_band_sk
        inventory: inv_date_sk,inv_item_sk,inv_warehouse_sk
        item: i_item_sk
        promotion: p_promo_sk
        reason: r_reason_sk
        ship_mode: sm_ship_mode_sk
        store: s_store_sk
        store_returns: sr_item_sk,sr_ticket_number
        store_sales: ss_item_sk,ss_ticket_number
        time_dim: t_time_sk
        warehouse: w_warehouse_sk
        web_page: wp_web_page_sk
        web_returns: wr_order_number,wr_item_sk
        web_sales: ws_item_sk,ws_order_number
        web_site: web_site_sk

gpdb_user: "{{ ansible_env.USER }}"
gpdb_install_path: /usr/local/gpdb/
gpdb_database_path: "{{ ansible_env.HOME }}/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/"

gpdb_default_config:
    gpdb_user: "{{ gpdb_user }}"
    gpdb_install_path: "{{ gpdb_install_path }}"
    gpdb_database_path: "{{ gpdb_database_path }}"
    gpdb_env:
      PGPORT: 7000
      PGUSER: "{{ gpdb_user }}"
      PGDATABASE: postgres
      PGDATA: "{{ gpdb_database_path }}"
      PGAPPNAME: tpcds_datagen
      PATH: "{{ gpdb_install_path }}/bin:{{ ansible_env.PATH }}"
