postgres_database_path: "{{ ansible_env.HOME }}/postgres_db_2"

postgres_configuration:
    tablespaces:
        - {tablespace: 'ts_data01', path: '/data01/ts_data01_2'}
        - {tablespace: 'ts_data02', path: '/data02/ts_data02_2'}
        - {tablespace: 'ts_data03', path: '/data03/ts_data03_2'}
    databases:
        - {database: 'zedstore', tablespace: 'ts_data01', gen_data: True, default_am: 'zedstore'}
        - {database: 'tpcds', tablespace: 'ts_data03', gen_data: True, default_am: 'heap'}
    gucs:
        - {guc: 'shared_buffers', value: '10GB'}
        - {guc: 'maintenance_work_mem', value: '4GB'}

tpcds_config:
    datagen_path_prefix: /data02/tpcds_datagen
