postgres_database_path: "{{ ansible_env.HOME }}/postgres_db"

postgres_config:
    tablespaces:
         ts_data01:
             path: /data01/ts_data01
             tablespace_options:
                 seq_page_cost: 2.5
                 random_page_cost: 2.5
                 effective_io_concurrency: 1
         ts_data02:
             path: /data02/ts_data02
             tablespace_options:
                 seq_page_cost: 2.5
                 random_page_cost: 2.5
                 effective_io_concurrency: 1
         ts_data03:
             path: /data03/ts_data03
             tablespace_options:
                 seq_page_cost: 2.5
                 random_page_cost: 2.5
                 effective_io_concurrency: 1
    databases:
        zedstore:
            tablespace: 'ts_data01'
            configuration_parameters:
                default_table_access_method: 'zedstore'
                search_path: 'tpcds, \"$user\", public'
        tpcds:
            tablespace: 'ts_data03'
            configuration_parameters:
                search_path: 'tpcds, \"$user\", public'
    gucs:
        shared_buffers: 10GB
        max_wal_size: 1GB
        checkpoint_flush_after: 1MB
        max_parallel_workers: 8
        max_parallel_maintenance_workers: 8
        maintenance_work_mem: 4GB
        log_statement: all
        effective_cache_size: 32GB

tpcds_config:
    datagen_path_prefix: /data02/tpcds_datagen
    datagen_scale: 1
    databases:
        - zedstore
        - tpcds

gpdb_tpcds_config:
    datagen_scale: 1
    databases:
        - tpcds
