postgres_database_path: "{{ ansible_env.HOME }}/postgres_db"

postgres_config:
    tablespaces:
        - {tablespace: 'ts_data01', path: '/data01/ts_data01'}
        - {tablespace: 'ts_data02', path: '/data02/ts_data02'}
        - {tablespace: 'ts_data03', path: '/data03/ts_data03'}
    databases:
        - {database: 'zedstore', tablespace: 'ts_data01', gen_data: True, default_am: 'zedstore'}
        - {database: 'tpcds', tablespace: 'ts_data03', gen_data: True, default_am: 'heap'}
    gucs:
        - {guc: 'shared_buffers', value: '10GB'}
        - {guc: 'maintenance_work_mem', value: '4GB'}
        - {guc: 'max_wal_size', value: '1GB'}
        - {guc: 'checkpoint_flush_after', value: '1MB'}
        - {guc: 'max_parallel_workers', value: '8'}
        - {guc: 'max_parallel_maintenance_workers', value: '8'}
        - {guc: 'effective_cache_size', value: '32GB'}

tpcds_config:
    datagen_path_prefix: /data02/tpcds_datagen
    datagen_scale: 1
