postgres_config:
    databases:
        zedstore:
            tablespace: 'pg_default'
            configuration_parameters:
                default_table_access_method: 'zedstore'
                search_path: 'tpcds, \"$user\", public'
        tpcds:
            tablespace: 'pg_default'
            configuration_parameters:
                search_path: 'tpcds, \"$user\", public'
    gucs:
        shared_buffers: 10GB
        max_wal_size: 1GB
        checkpoint_flush_after: 1MB
        max_parallel_workers: 8
        max_parallel_maintenance_workers: 8
        maintenance_work_mem: 4GB
        log_statement: all
        effective_cache_size: 32GB

tpcds_config:
    datagen_scale: 2
    databases:
        - zedstore
        - tpcds
    tpcds_tables:
        - inventory
        - customer_demographics
        - date_dim
