---
gpdb_config:
    databases:
        - {database: 'tpcds', tablespace: 'pg_default', gen_data: True, default_am: 'heap'}
postgres_config:
    databases:
        - {database: 'zedstore', tablespace: 'pg_default', gen_data: True, default_am: 'zedstore'}
