postgres_version: zedstore
postgres_repo: https://github.com/greenplum-db/postgres

postgres_config:
    databases:
        zedstore:
            tablespace: 'ts_data01'
            configuration_parameters:
                default_table_access_method: 'zedstore'
        tpcds:
            tablespace: 'ts_data03'
    gucs:
        shared_buffers: 4GB
        max_wal_size: 1GB
        checkpoint_flush_after: 1MB
        max_parallel_workers: 8
        max_parallel_maintenance_workers: 8
        maintenance_work_mem: 4GB
        log_statement: all
        effective_cache_size: 32GB

build_postgres_config:
    enable_cassert: False
    with_lz4: True
    cflags: "-O2 -fno-omit-frame-pointer"

tpcds_config:
    datagen_path_prefix: /usr/local/pgsql/data/tpcds_datagen
    datagen_scale: 270
    databases:
        - zedstore
        - tpcds

lvm_devices:
    - /dev/nvme0n1
    - /dev/nvme0n2
    - /dev/nvme0n3
    - /dev/nvme0n4
    - /dev/nvme0n5
    - /dev/nvme0n6
