---
postgres_user: "{{ ansible_env.USER }}"
postgres_install_path: /usr/local/pgsql/
postgres_database_path: /usr/local/pgsql/data

postgres_default_config:
    postgres_user: "{{ postgres_user }}"
    postgres_install_path: "{{ postgres_install_path }}"
    postgres_database_path: "{{ postgres_database_path }}"
    tablespaces: {}
    #     tmpspace: /tmp/tmpspace
    #     tablespace_options:
    #         seq_page_cost: 2.5
    #             random_page_cost: 2.5
    #             effective_io_concurrency: 2
    databases: {}
        #    zedstore:
        #        tablespace: 'pg_default'
        #        configuration_parameters:
        #            default_table_access_method: 'zedstore'
    gucs:
        shared_buffers: 1GB
        max_wal_size: 1GB
        checkpoint_flush_after: 1MB
        max_parallel_workers: 8
        max_parallel_maintenance_workers: 2
        maintenance_work_mem: 1GB
        log_statement: all
    postgres_env:
      PGPORT: 5432
      PGUSER: "{{ postgres_user }}"
      PGDATABASE: postgres
      PGDATA: "{{ postgres_database_path }}"
      PGAPPNAME: tpcds_datagen
      PATH: "{{ postgres_install_path }}/bin:{{ ansible_env.PATH }}"
