---
- name: Set variables
  set_fact:
    _postgres_config: "{{ postgres_default_config | combine(postgres_config | default({}), recursive=True) }}"

- include: packages.yaml
- include: gen_cluster.yaml
  environment: "{{ _postgres_config.postgres_env }}"
