---
- name: Build database
  command: "initdb"
  args:
    creates: "{{ _postgres_config.postgres_database_path }}/postgresql.conf"

- name: Start database
  command: "pg_ctl -l /tmp/logfile start"
  args:
    creates: "{{ _postgres_config.postgres_database_path }}/postmaster.pid"

- name: Set system GUCS
  command: "psql postgres -c \"ALTER SYSTEM SET {{item.guc}} TO '{{item.value}}';\""
  with_items: "{{ _postgres_config.gucs }}"

- name: Restart database
  command: "pg_ctl -l /tmp/logfile restart"

- name: Create tablespace directories
  file:
    path: "{{item.path}}"
    state: directory
    mode: 0700
    owner: "{{ _postgres_config.postgres_user }}"
  with_items: "{{ _postgres_config.tablespaces }}"
  when: _postgres_config.tablespaces is defined
  become: yes

- name: Drop databases
  command: "dropdb {{item.database}}"
  ignore_errors: yes
  with_items: "{{ _postgres_config.databases }}"

- name: Create tablespaces
  postgresql_tablespace:
    name: "{{ item.tablespace }}"
    location: "{{ item.path }}"
    login_host: localhost
    login_user: "{{ _postgres_config.postgres_env.PGUSER }}"
    port: "{{ _postgres_config.postgres_env.PGPORT }}"
    db: "{{ _postgres_config.postgres_env.PGDATABASE }}"
    set:
      random_page_cost: 1
      seq_page_cost: 1
  with_items: "{{ _postgres_config.tablespaces }}"

- name: Create databases
  postgresql_db:
    name: "{{ item.database }}"
    tablespace: "{{ item.tablespace }}"
    login_host: localhost
    login_user: "{{ _postgres_config.postgres_env.PGUSER }}"
    port: "{{ _postgres_config.postgres_env.PGPORT }}"
    maintenance_db: "{{ _postgres_config.postgres_env.PGDATABASE }}"
  with_items: "{{ _postgres_config.databases }}"

- name: Set postgres search path for {{ _postgres_config.postgres_env.PGUSER }}
  command: "psql -v ON_ERROR_STOP=1 -q -A -t -c 'ALTER USER {{ _postgres_config.postgres_env.PGUSER }} SET search_path=tpcds,public;'"

