---
- name: Set variables
  set_fact:
    _postgres_config: "{{ postgres_default_config | combine(postgres_config, recursive=True) }}"

- include: gen_cluster.yaml
  environment: "{{ _postgres_config.postgres_env }}"
