---

#- name: Check if database is up and running
#  command: "{{postgres_install_path}}/psql postgres -c 'select 1'"
#  register: dbstatus
#  ignore_errors: yes

- name: Build database
  command: "{{postgres_install_path}}/initdb -D {{database_path}}"
  args:
    creates: "{{database_path}}/postgresql.conf"

- name: Start database
  command: "{{postgres_install_path}}/pg_ctl -D {{database_path}} -l /tmp/logfile start"
  args:
    creates: "{{database_path}}/postmaster.pid"

- name: Set system GUCS
  command: "{{postgres_install_path}}/psql postgres -c \"ALTER SYSTEM SET {{item.guc}} TO '{{item.value}}';\""
  with_items: "{{gucs}}"

- name: Restart database
  command: "{{postgres_install_path}}/pg_ctl -D {{database_path}} -l /tmp/logfile restart"

- name: Create tablespace directories
  file:
    path: "{{item.path}}"
    state: directory
    mode: 0755
    owner: "{{lookup('env', 'USERNAME')}}"
  with_items: "{{tablespaces}}"
  become: yes

- name: Drop databases
  command: "{{postgres_install_path}}/dropdb {{item.database}}"
  ignore_errors: yes
  with_items: "{{databases}}"

- name: Drop tablespaces
  command: "{{postgres_install_path}}/psql -v ON_ERROR_STOP=1 postgres -c \"drop tablespace {{item.tablespace}}\""
  ignore_errors: yes
  with_items: "{{tablespaces}}"

- name: Create tablespaces
  command: "{{postgres_install_path}}/psql -v ON_ERROR_STOP=1 postgres -c \"create tablespace {{item.tablespace}} location '{{item.path}}'\""
  with_items: "{{tablespaces}}"

- name: Create databases
  command: "{{postgres_install_path}}/createdb {{item.database}} -D {{item.tablespace}}"
  ignore_errors: yes
  with_items: "{{databases}}"

