#!/bin/bash

export ANSIBLE_GCP_PROJECT=
export ANSIBLE_GCP_ZONE=
export ANSIBLE_GCP_INSTANCE_NAME=
export ANSIBLE_GCP_INSTANCE_TYPE=n1-standard-1
export ANSIBLE_GCP_NETWORK_NAME=default
export ANSIBLE_USER=
export ANSIBLE_SSH_KEY_FILE=
export GCP_SERVICE_ACCOUNT_FILE=
