---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tpcds-gp4k
data:
  DATAGEN_SCALE: "1"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpcds-gp4k
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: microk8s-hostpath

